# Konfigurasi Koneksi Database MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_pengaduan_beacukai
spring.datasource.username=root
spring.datasource.password=

# Konfigurasi JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Batas untuk satu file
spring.servlet.multipart.max-file-size=100MB
# Batas untuk total ukuran request (jika ada beberapa file)
spring.servlet.multipart.max-request-size=105MB
server.port=${PORT:8080}
openai.api.key=
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=EMAILANDA@gmail.com
spring.mail.password=PASSWORD_APP_EMAIL
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Configuration
beacukai.app.jwtSecret=RahasiaNegaraBeaCukaiIniSangatPanjangDanAmanSekali1234567890
beacukai.app.jwtExpirationMs=86400000
# (86400000 ms = 24 Jam. Token akan hangus setelah sehari)